### ISSUE TITLE
what is domain options for, why not just use one path arg?

### ISSUE THREAD

**Issue by pajtai** [solid-stack/http.service#1]
Sending requests to `/my/request` has an awkward signature of `.get('', '/my/request')`, why not just have the first argument be the full url?

**Comment by willphdavies** [comment]
Because you may be querying API endpoints from separate apps (third party
stuff), plus if you are running the service from the server, the domain
will be different, but the endpoint will be the same (local host vs
domain.com). The domain for a set of endpoints, to me, is a configuration
of the app
